### ISSUE TITLE
Criação de issue Template

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#1]
Nessa issue deve ser realizada a criação do template de Issue. O template deve conter o passo a passo de como criar uma issue para o projeto.

## Task

- [x] Elaboração do template de issue.

**Comment by joaovitor3** [comment]
Issue template criado na branch gh-pages.

Foi criado nessa branch para depois ser utilizado junto ao github pages

**Comment by vitorandos** [comment]
Havíamos discutido sobre não colocar os critérios de aceitação no template já que nem sempre eles estariam definidos no momento de criação da issue. Contudo, levando em conta algumas das issues criadas, acredito que seja importante recolocá-lo, apontando este caso de exceção em que, portanto, os critérios seriam adicionados pelo PO em um comentário.
