### ISSUE TITLE
Treinamento de Python

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#10]
Realizar treinamento de python através de vídeo-aulas e cursos online.

Alguns cursos e vídeo aulas recomendados, caso achem algum outro curso ou recurso interessante sintam-se a vontade em comentar a issue com esses : 
- [x] [google python class](https://developers.google.com/edu/python/)
- [x] [Vídeo aula com conceitos introdutórios sobre python](https://www.youtube.com/watch?v=f79MRyMsjrQ)
- [x] [The Hitchhiker’s Guide to Python](https://docs.python-guide.org/)

Critérios de aceitação:
- [x] Equipe de MDS estar confortável para começar a desenvolver quando solicitado.

**Comment by ghost** [comment]
Estudos sobre conceitos introdutórios da linguagem Python durante a tarde/noite

**Comment by caiovfernandes** [comment]
Estudando Python.
Documentando aqui: [https://www.notion.so/043704bc30314b018a80db4d650b8438?v=d74d749e4c754f089db1ccffca20d467](url)

**Comment by ErickGiffoni** [comment]
Já tenho um certo conhecimento em Python, pois já trabalhei um pouco com a linguagem. Inclusive tenho um script interativo de minha autoria para ensinar o básico de Python. Pretendo revisar em breve.

**Comment by guilherme-mendes** [comment]
Finalizado o estudo de Python recomendado.
Indico esse material para complementar os estudos.
[Python - Escreva seus primeiros programas.pdf](https://github.com/fga-eps-mds/2019.1-Grupo-3/files/2996686/Python.-.Escreva.seus.primeiros.programas.pdf)

**Comment by sudjoao** [comment]
Estudando Python a partir do livro "Python: Guia prático do básico ao avançado" por F. V. C. Santos, Rafael.

**Comment by guilherme-mendes** [comment]
Python Orientado a Objetos.
https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc

**Comment by vitorandos** [comment]
A lição 11 desse tutorial fala um pouco sobre classes em Python https://www.codecademy.com/learn/learn-python

**Comment by ErickGiffoni** [comment]
Esse link que o @guilherme-mendes  postou do youtube é muito bom! O rapaz explica bem e numa velocidade boa.

**Comment by ErickGiffoni** [comment]
Pessoal, recomendo o seguinte livro para aprender Orientação a objetos em Python : Introdução à orientação a objetos com C++ e Python; Orlando Saraiva Jr.; Novatec, 2017

**Comment by caiovfernandes** [comment]
Estudando Python POO
Documentando aqui: [https://www.notion.so/Python-POO-28c9845576f1449289c9fbc1cb8cf7b4](url)
