### ISSUE TITLE
Revisão da Documentação 

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#167]
## Descrição da Issue
Revisão ortográfica e validação de documentos referentes ao produto e projeto

### Tasks: 
- [x] Revisão ortográfica
- [x] Validação dos documentos

### Critérios de aceitação
- [x] Deve estar condizente com o projeto

**Comment by vitorandos** [comment]
Revisamos a documentação, corrigindo erros ortográficos, refinando conceitos e atualizando documentos segundo nossa estratégia e modelo de negócios.
