### ISSUE TITLE
Elaboração de Rich Pictures

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#19]
## Descrição da Issue
Cada MDS's deve elaborar um rich picture sobre o projeto a ser desenvolvido

### Tasks: 
- [x] Rich picture 1
- [x] Rich picture 2
- [x] Rich picture 3
- [x] Rich picture 4
- [x] Rich picture 5

**Comment by ErickGiffoni** [comment]
Rich picture realizada com sucesso. 
25/03/2019 - 14:55h

**Comment by ghost** [comment]
Rich picture feita e adicionada ao drive!
25/03/2019 - 19:09h

**Comment by ErickGiffoni** [comment]
Picture adicionada ao drive do grupo.
26/03/2019 - 12:41

**Comment by caiovfernandes** [comment]
Picture foi adicionada ao Drive 
26/03/2019 - 07:30AM

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Rich picture clara segundo o escopo do projeto

**Comment by guilherme-mendes** [comment]
Rich picture concluída e adicionada ao [Drive](https://drive.google.com/drive/folders/1ToHs6qQf1RqhZi4eZNUSKZi5c5ZmeJju).
28/03/2019 - 21:34

**Comment by sudjoao** [comment]
Rich picture feita e adicionada ao Drive
28/03/2019 - 21:40
