### ISSUE TITLE
Cronjob para agendamento de tarefas

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#199]
Nessa issue deve ser implementado o cronjob para agendamento de tarefas do gitlab, no qual o usuário pode registrar o horário que ele queira receber o relatório.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [ ] Usuário conseguir agendar horários
- [ ] Enviar relatórios

### Critérios de aceitação

- [ ] Testado
- [ ] Usuário receber relatório no horário agendado.

**Comment by BrunoOliveiraDantas** [comment]
Essa issue não será mais implementada, por conta da redução de escopo, caso exista alguma oportunidade eu gostaria de adiciona-lá novamente.

**Comment by ErickGiffoni** [comment]
@BrunoOliveiraDantas Verdade, se possível vamos tentar fazer essa história . Acho que valerá a pena.
