### ISSUE TITLE
Treinamento de git

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#2]
Realizar treinamento de git para capacitação dos membros de MDS.

Tasks:
- [x] Criação de repositório para realização do treinamento
- [x] Realizar treinamento com todos os integrantes de MDS

Critérios de aceitação:
Os membros de MDS ao finalizarem o treinamento, devem ser capazes de: 
- [x] Criar branches a partir de uma branch existente;
- [x] Realização de conflitos;
- [x] Conseguir adicionar arquivos locais ao repositório remoto do github;
- [x] Saber utilizar comandos básicos como: git add, git commit, git push, git pull, git merge, git log, git status;
- [x] Abrir pull requests.

**Comment by joaovitor3** [comment]
Treinamento já realizado em um outro [repositório ](https://github.com/joaovitor3/dojo_git_eps).

Foi solicitado a criação de funções de uma calculadora em um arquivo .c, para geração de conflitos e devidas resoluções entre os membros de MDS, além da abertura de pull requests entre a branch em que o membro modificou o arquivo .c para uma branch de desenvolvimento.

**Comment by ErickGiffoni** [comment]
O treinamento gerou um resultado positivo para mim.
