### ISSUE TITLE
Redigir reunião/entrevista com clientes

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#24]
## Descrição da Issue
Redigir documento relatando os principais pontos discutidos na reunião com clientes sobre o software a ser desenvolvido. 

### Tasks: 
- [x] Descrever problema chave
- [x] Descrever subproblemas
- [x] Descrever funcionalidades

**Comment by vitorandos** [comment]
Critérios de aceitação:
- [x] Todas tasks concluídas
- [x] Conteúdo inteligível
