### ISSUE TITLE
US37 - Eu, como usuário, desejo que a Ada me informe quando um pull request receber uma solicitação de revisão para que eu tenha conhecimento do andamento do projeto.

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#244]
## Descrição da Issue
Eu, como usuário, desejo que a Ada me informe quando um pull request receber uma solicitação de revisão para que eu tenha conhecimento do andamento do projeto.
### Tasks: 

- [x] Elaborar fluxo de conversa
- [x] Tratar json recebido de acordo com o evento disparado.

### Critérios de aceitação

- [x] Testes feitos
- [x] Mensagens validadas
- [x] Notificação funcionando

**Comment by vitorandos** [comment]
Nessa história, todos os usuários que têm o repositório cadastrado na Ada recebem a notificação de solicitação de revisão do PR.

**Comment by ateldyfilho** [comment]
Essa História foi adicionada durante a sprint 10 e feita juntamente com a #218 no PR https://github.com/fga-eps-mds/2019.1-ADA-github/pull/8
