### ISSUE TITLE
US38 - Eu, como usuário, desejo que a Ada me informe quando um pull request for aberto para que eu tenha conhecimento do andamento do projeto.

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#245]
## Descrição da Issue
Eu, como usuário, desejo que a Ada me informe quando um pull request for aberto para que eu tenha conhecimento do andamento do projeto.

### Tasks: 
- [x] Elaborar fluxo de conversa
- [x] Tratar json recebido de acordo com o evento disparado.

### Critérios de aceitação

- [x] Testes feitos
- [x] Mensagens validadas
- [x] Notificação funcionando

**Comment by vitorandos** [comment]
Nessa história, todos os usuários que têm o repositório cadastrado na Ada recebem a notificação de abertura do PR.

**Comment by ateldyfilho** [comment]
Essa História foi adicionada durante a sprint 10 e feita juntamente com a #218 no PR https://github.com/fga-eps-mds/2019.1-ADA-github/pull/8
