### ISSUE TITLE
US33 - Eu, como usuário, desejo que a Ada me informe quando um comentário de issue for feito.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#246]
## Descrição da Issue
Eu, como usuário, desejo que a Ada me informe quando um comentário de issue for feito no repositório cadastrado.

### Tasks: 

- [x] Elaborar fluxo de conversa
- [x] Tratar json recebido de acordo com o evento disparado.

### Critérios de aceitação

- [x] Testes feitos
- [x] Mensagens validadas
- [x] Notificação funcionando

**Comment by vitorandos** [comment]
Nessa história, todos os usuários que têm o repositório cadastrado na Ada recebem a notificação de comentário de issue.

**Comment by ateldyfilho** [comment]
Essa História foi adicionada durante a sprint 10 e feita juntamente com a #218 no PR https://github.com/fga-eps-mds/2019.1-ADA-github/pull/8
