### ISSUE TITLE
Criar página no GitHub Pages

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#26]
## Descrição da Issue
Criação de página no GitHub Pages para disponibilizar documentos do projeto.

### Tasks: 
- [x] Criar página no gitHub Pages 
- [x] Verificar se não há problemas

**Comment by joaovitor3** [comment]
Página no github pages criada utilizando o docsify.

Faltam apenas colocarmos alguma imagem do produto na landing page e definirmos os tópicos da sidebar
