### ISSUE TITLE
Aprimorar fluxo de conversa de retorno de colaboradores

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#274]
## Descrição da Issue
No teste em uso realizado (#267), o fluxo de conversa quando se quer saber quem está colaborando no projeto (conforme história #234) não foi muito efetivo. O objetivo dessa issue é aprimorá-lo através de, por exemplo, criação de novas intents.

### Tasks: 
- [x] Criar novas intents para o retorno dos colaboradores

### Critérios de aceitação
- [x] Validação pelo PO do fluxo atualizado

**Comment by vitorandos** [comment]
Alguns exemplos de intents executadas durante o teste em uso:

- membros
- quem contribui
- colaboradores

Além disso, verifiquei que a maioria das intents atuais possuem "do meu projeto" na sua estrutura, é importante ressaltar que nem sempre o usuário fala com essas palavras, por exemplo durante o #267 Teste em Uso, essa maneira não foi utilizada. Outra maneira possível é "do meu repositório" ou simplesmente nada como nos exemplos acima.

**Comment by vitorandos** [comment]
Outro exemplo que apareceu durante a realização dos testes em uso:

- quem colabora com esse repositório?

**Comment by sudjoao** [comment]
Fechando a issue pois o pull request foi aceito.
