### ISSUE TITLE
Garantir que o usuário se cadastre antes de fazer pedidos a Ada

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#275]
## Descrição da Issue
Conforme notado no #267 Teste em Uso, mesmo que o usuário ainda não tenha se cadastrado, a Ada tenta executar seus pedidos, por exemplo, geração do relatório dos repositórios. O objetivo dessa issue é trazer meios para garantir que o usuário se cadastre antes de realizar as atividades.

Contudo, é importante destacar que não se deve obrigar o usuário a se cadastrar tanto no GitHub quanto no GitLab para utilizar a Ada, apenas o que ele desejar usar deve ser necessário.

O ideal é que, quando o usuário pedir algo do GitHub, por exemplo, criar uma issue, sem ter repositório do GitHub cadastrado, a Ada oriente-o para tal. O mesmo para o GitLab. Atenção: se o usuário tentar criar uma issue, com repositório do GitHub cadastrado mas sem repositório do GitLab, a funcionalidade deve ser executada normalmente, afinal apenas o GitHub é necessário para tal.

### Critérios de aceitação
- [x] Ada não tenta executar ações relacionadas aos repositórios sem que um esteja cadastrado
- [x] Quando o usuário tentar solicitar algo relacionado a um repositório que ele ainda não tenha cadastrado, Ada orientá-lo para o cadastro

**Comment by vitorandos** [comment]
Ainda não sei de fato como solucionar essa problemática, portanto deixei as tasks em branco e solicito o auxílio do resto da equipe e da comunidade a fim de elaborar a solução e marco a issue como help wanted.

**Comment by ErickGiffoni** [comment]
@vitorandos Uma alternativa pode ser cadastrar o usuário no banco de dados e atribuir uma variável booleana que diz se ele está cadastrado ou não . Aí antes de iniciar qualquer custom action, consultar essa variável no banco

**Comment by vitorandos** [comment]
Obrigado pela sugestão, @ErickGiffoni. Infelizmente, isso ainda não resolve nosso problema. Para esse caso, podemos verificar se os atributos de project não estão vazios. O maior problema está em impedir que a Ada execute a intent quando tais atributos estiverem vazios.

**Comment by sudjoao** [comment]
O @lucasfcm9 e eu começamos a fazer essa issue, e como tinhamos previsto durante a reunião é possível descobrir se o usuário está cadastrado, ou não, através do slots do próprio rasa.

**Comment by sudjoao** [comment]
Fechando a issue pois o pull request foi aceito.
