### ISSUE TITLE
Aprimorar fluxo de conversa para monitoramento do estado da aplicação

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#276]
## Descrição da Issue
Durante a realização do #267 Teste em Uso, verificou-se que a Ada, ao perguntar se o usuário quer que ela monitore sua aplicação, não é muito clara. Na realização do teste, a princípio o usuário entendeu a pergunta como outra coisa coisa, depois, vendo o que era de fato, tentou cancelar o pedido, e no que, finalmente, não foi compreendido pela Ada. Imagem desse exemplo no comentário a seguir.

### Tasks: 
- [x] Deixar a pergunta e informações sobre o monitoramento do estado da aplicação mais claros

### Critérios de aceitação
- [x] Validado pelo PO

**Comment by vitorandos** [comment]
Exemplo citado na descrição da issue:

<img width="653" alt="Captura de Tela 2019-06-12 às 15 51 26" src="https://user-images.githubusercontent.com/15351084/59378213-2cb96080-8d2a-11e9-9d09-c4212bf8951a.png">

**Comment by vitorandos** [comment]
Exemplo citado na descrição da issue:

<img width="653" alt="Captura de Tela 2019-06-12 às 15 51 26" src="https://user-images.githubusercontent.com/15351084/59378302-64c0a380-8d2a-11e9-9bc8-5acd104749b3.png">

**Comment by sudjoao** [comment]
Fechando a issue pois o pull request foi aceito.
