### ISSUE TITLE
Links úteis para o projeto

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#28]
## Descrição da Issue
Adição de conteúdos relevantes que podem auxiliar a equipe no desenvolvimento do projeto.

### Tasks: 
- [x] Destacar links com sua devida descrição

**Comment by guilherme-mendes** [comment]
Estudo sobre boas práticas de ChatBots.
https://github.com/lappis-unb/tais/wiki/Estudo-sobre-melhores-pr%C3%A1ticas-de-bots#refer%C3%AAncias-bibliogr%C3%A1ficas

**Comment by guilherme-mendes** [comment]
Uma coleção de coisas incríveis sobre o ChatOps.
https://github.com/exAspArk/awesome-chatops

**Comment by ErickGiffoni** [comment]
Projeto Bot do Lappis : https://github.com/lappis-unb/rasa-ptbr-boilerplate

Rasa Docs : https://rasa.com/docs/nlu/master/customcomponents/

**Comment by ErickGiffoni** [comment]
Link do webinar de hoje sobre Rasa : https://www.youtube.com/watch?v=zL8zCbmfLwM&feature=youtu.be

**Comment by caiovfernandes** [comment]
Tutorial inicial para o Rasa: [``](https://rasa.com/docs/get_started_step1/)

**Comment by caiovfernandes** [comment]
Tutorial inicial para o Rasa: [https://rasa.com/docs/get_started_step1/](url)

**Comment by caiovfernandes** [comment]
Introdução à Microserviços: [https://www.thoughtworks.com/pt/insights/blog/microservices-nutshell](url)
Introdução à Flask: http://pythonclub.com.br/what-the-flask-pt-1-introducao-ao-desenvolvimento-web-com-python.html#o_que_e_flask
Introdução ao React: https://reactjs.org/tutorial/tutorial.html#what-is-react

**Comment by caiovfernandes** [comment]
Bot's no Telegram: [https://core.telegram.org/bots](url)

**Comment by ErickGiffoni** [comment]
Modelo bacana de apresentação de um produto :
[https://docs.google.com/presentation/d/1wTS0i3isy4SovthPB1crV-O-93jMfelgu4m1DEt6DAE/edit#slide=id.gcb9a0b074_1_0](url)

Obs.: podemos usar de referência para a release 1.

**Comment by ErickGiffoni** [comment]
Encontrei um livro gratuito de MongoDB :
[http://file.allitebooks.com/20160130/Practical%20MongoDB.pdf](url)
Pode nos ser útil
