### ISSUE TITLE
Elaborar documento de visão

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#3]
Tasks:
- [x] Realizar a elaboração do documento de visão de acordo com o[ template](https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html) utilizado no treinamento.

Critérios de aceitação:
- [x] Todos os tópicos de acordo com o template estejam preenchidos.

**Comment by ErickGiffoni** [comment]
O grupo está reunido para elaborar o documento. 
21/03/2019 - 13:20h às 14h.

**Comment by ErickGiffoni** [comment]
Terminando o tópico 2 . 
22/03/2019 - 8:14h

**Comment by ErickGiffoni** [comment]
Revisão dos tópicos 1 e 2 e complementação do subtópico 2.3 . Notem que ao longo do documento existe a "tag" $nome , que deve ser substituída quando decidirmos o nome oficial do nosso ChatOps.
22/03/2019 - 10:31h
