### ISSUE TITLE
Treinamento de flask

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#32]
Realizar treinamento de flask através de vídeo-aulas e cursos online.

Alguns cursos e vídeo aulas recomendados, caso achem algum outro curso ou recurso interessante sintam-se a vontade em comentar a issue com esses : 
- [x] [Playlist com conceitos introdutórios sobre flask](https://www.youtube.com/playlist?list=PL3BqW_m3m6a05ALSBW02qDXmfDKIip2KX)
- [x] [Tutorial da documentação oficial do flask](http://flask.pocoo.org/docs/1.0/tutorial/#tutorial)

Critérios de aceitação:
- [x] Equipe de MDS estar confortável para começar a desenvolver quando solicitado.

**Comment by ErickGiffoni** [comment]
Aula 1 - 

Tive um erro ao rodar o arquivo app.py pela terceira vez : deu um Traceback e falou que o endereço local já existia e já estava em uso...

self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use


Como contornar isso ?﻿

**Comment by joaovitor3** [comment]
@ErickGiffoni 
Esse erro provavelmente é porque você já está usando a porta que quer rodar o app.py.
Tenta ver os processos ativos pelo terminal e mate os que estiverem na mesma porta que o flask usa(5000 se não me engano) .

Esse link pode ser útil:
https://stackoverflow.com/questions/19071512/socket-error-errno-48-address-already-in-use

**Comment by ErickGiffoni** [comment]
Já consegui. [solução aqui](https://stackoverflow.com/questions/19071512/socket-error-errno-48-address-already-in-use/19071568#19071568)

**Comment by ErickGiffoni** [comment]
Isso mesmo, mano @joaovitor3 , valeu !

**Comment by joaovitor3** [comment]
Novo treinamento realizado nesse [repositório](https://github.com/joaovitor3/treinamento-flask-mongo/tree/master).
No treinamento foram utilizadas as tecnologias:
- Docker
- Mongo
- Flask

Após o treinamento a equipe de MDS deve ser capaz de:
- [x] Realizar registros no banco de dados;
- [x] Realizar buscas na base de dados por algum parâmetro utilizando o flask py mongo.

**Comment by guilherme-mendes** [comment]
Treinamento concluído! Foram criadas as rotas de busca (método GET) e de registro de usuário (método POST), com as tecnologias citadas.

Resolução do treinamento no seguinte [repositório](https://github.com/joaovitor3/treinamento-flask-mongo/tree/rota_busca_usuario_guilherme).
