### ISSUE TITLE
Treinamento de metodologias e práticas ágeis

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#4]
Realizar treinamento sobre metodologias e práticas ágeis:

Tasks:
- [x] Explicar metodologias ágeis
- [x] Explicar princípios e valores do ágil
- [x] Explicar o manifesto ágil

Critérios de aceitação:
- [x] Equipe de MDS ter maduridade em relação principais práticas ágeis

**Comment by ErickGiffoni** [comment]
O treinamento já foi realizado pelos EPS's. Há algo mais ?

**Comment by vitorandos** [comment]
O treinamento foi realizado no dia 19 de março de 2019, presencialmente, cumprindo todas as tarefas.

Todos os materias utilizados, bem como links úteis, podem ser encontrados no link: https://drive.google.com/drive/folders/1vR3oC5eAWG1b5NxXzyS6lTgtRE-Es1hS?usp=sharing
