### ISSUE TITLE
DS01- Eu, como desenvolvedor, quero que todo o ambiente de desenvolvimento da Ada esteja uniformizado para padronizar o desenvolvimento.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#52]
## Descrição da Issue

O ambiente de desenvolvimento da Ada deve está uniformizado para padronizar o desenvolvimento utilizando o Docker, contendo todos os comandos que o responsável pelo DevOps possa chamar na linha de comando, para montar uma imagem para disponibilizar o ambiente de desenvolvimento do projeto.

### Tarefas

- [x] Montar o Dockerfile para o ambiente do projeto

**Comment by ateldyfilho** [comment]
@vitorandos critérios de aceitação;
@joaovitor3 tasks

**Comment by joaovitor3** [comment]
A branch em que estava trabalhando sofreu merge com as branches de outros pareamentos.
Com isso não será necessário um pull request da branch 1-DockerizaAmbiente para  a devel.
Posso fechar a issue?

**Comment by vitorandos** [comment]
Como o realizado nessa Issue já subiu à devel através de outra, fecho-a.
