### ISSUE TITLE
DS02 - Eu, como desenvolvedor, quero criar um banco de dados que guarde informações do Telegram para conseguir comunicação estável com a Ada.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#54]
## Descrição da Issue

Criar um banco de dados que guarde informações do Telegram para conseguir comunicação estável com a Ada com banco escolhido, MongoDB, orientado a documentos.

### Tasks: 
- [x] Modelar Banco de dados da aplicação

**Comment by ateldyfilho** [comment]
@vitorandos definir critérios de aceitação;

**Comment by ErickGiffoni** [comment]
Iniciados os estudos em MongoDB

**Comment by ErickGiffoni** [comment]
As informações do Telegram são a respeito do usuário e são passadas ao banco de dados via Telegram API , certo ? 
Imagino então que precisamos implementar a classe User do Diagrama de Classes, tópico 5.1 do documento de arquitetura. 
Como pegar as informações via Telegram API e passar para o banco ?

**Comment by vitorandos** [comment]
Sim, a classe User será necessária.

**Comment by ErickGiffoni** [comment]
O database deve ser MongoDB e deve ser orientado a documentos. Isso significa que devemos utilizar a [mongoengine](http://mongoengine.org/) ?

**Comment by ErickGiffoni** [comment]
Problemas : estou fazendo alguns códigos teste para conectar um programa a um banco de dados mongo , utilizando mongoengine nos programas. 
Os programas funcionam, eles executam sem problemas. 
Ai eu abro o app [Robo 3T](https://robomongo.org/download) , mas nao consigo fazer uma conexao localhost , e tenho o erro : 

Cannot connect to the MongoDB at localhost:27017. Error: Network is unreachable

Nao consigo resolver o problema. A ideia de conectar na localhost pelo app Robo 3T é que ele mostra que voce realmente criou um banco de dados mongo.

Esses passos que estou fazendo são reproduções das aulas 11, 13, 14 e 16 do curso [MongoDB and Python: Quick start](https://www.udemy.com/mongodb-and-python-quickstart-with-mongoengine/), grátis da Udemy.

**Comment by ErickGiffoni** [comment]
Códigos do referido acima : 

program.py -> programa principal 

`import User
import mongo_setup

mongo_setup.initialize_mongo_connection()

batata = User

batata.name = input("name ? ")

print("name is " + str(batata.name))`

User.py -> classe usuário

`import mongoengine


class User(mongoengine.Document):
       name = mongoengine.StringField()`

mongo_setup.py -> inicializa o mongo db 

`import mongoengine


def initialize_mongo_connection():
        mongoengine.register_connection(alias='core', name='test')`

**Comment by caiovfernandes** [comment]
Erick, tente configurar seu ambiente mongo e subir o servidor local antes de tentar uma conexão no Robo3T.
Para configurar o mongo use o seguinte comando: `mongod --config /usr/local/etc/mongod.conf`
Depois, suba  o servidor inserindo o comando: `mongo`

**Comment by caiovfernandes** [comment]
Se não conseguir utilizando os passos acima provavelmente foi porque você não criou a pasta **data/db,** que é onde os arquivos do mongo são salvos.
Crie a pasta com o seguinde comando: `sudo mkdir -p /data/db`
Depois dê permissão para que o mongo possa acessá-la: `sudo chown -R  ` id -un `  /data/db`

Após essas configurações suba  o **Mongo daemon** utilizando o comando `mongod` para subir o servidor.
Depois, em outra janela do terminal, insira `mongo`.  Este comando irá executar o **Mongo Shell**, que é uma aplicação para acessar os dados no MongoDB.

**Comment by caiovfernandes** [comment]
**Links úteis** para o desenvolvimento da issue:

1. Python-telegram-bot: [https://github.com/python-telegram-bot/python-telegram-bot](url)

2. Telegram BOT API:  [https://core.telegram.org/bots/api#authorizing-your-bot](url)

3. Bots: An introduction for developers: [https://core.telegram.org/bots#botfather](url)

4. Youtube channel for MongoDB: [https://www.youtube.com/user/TechGuyWeb/search?query=mongo](url) 

5. Connecting to MongoDB : [http://docs.mongoengine.org/guide/connecting.html](url)

**Comment by caiovfernandes** [comment]
Curso de MongoDB da Udemy finalizado.
Notações que considerei importantes documentei no Notion: [https://www.notion.so/Basics-with-MongoEngine-0756dbe31cfe4ac4b77a25efd123746f](url)

**Comment by ErickGiffoni** [comment]
> Se não conseguir utilizando os passos acima provavelmente foi porque você não criou a pasta **data/db,** que é onde os arquivos do mongo são salvos.
> Crie a pasta com o seguinde comando: `sudo mkdir -p /data/db`
> Depois dê permissão para que o mongo possa acessá-la: `sudo chown -R ` id -un ` /data/db`
> 
> Após essas configurações suba o **Mongo daemon** utilizando o comando `mongod` para subir o servidor.
> Depois, em outra janela do terminal, insira `mongo`. Este comando irá executar o **Mongo Shell**, que é uma aplicação para acessar os dados no MongoDB.

Não tá dando pra executar mongo e mongod ao mesmo tempo. Ao fazer mongod em outra aba do terminal, dá um erro : 
Failed to set up listener: SocketException: Address already in use

**Comment by ErickGiffoni** [comment]
Criei um protótipo da classe User. Devo commitar na branch da história ?

**Comment by joaovitor3** [comment]
Sim, você deve fazer como no [gitflow](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/gitflow).
Criando a branch a partir da devel com o nome:
2-CriarBancoDeDados, por exemplo e realizar o commit de acordo com o especificado na [política de commits](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/policies/commits)

**Comment by vitorandos** [comment]
O ideal é que você commit mesmo para que sua dupla de paramento tenha acesso ao código. Não se preocupe em haver mudanças na classe, isso é bem normal nessa fase de desenvolvimento.

**Comment by ErickGiffoni** [comment]
Não consigo matar essa aplicação/servidor : 

lsof -i:27017
COMMAND  PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mongod  9924 erick.giffoni   10u  IPv4 0xf750e32836181517      0t0  TCP localhost:27017 (LISTEN)

Mesmo com $ sudo kill 9924

Alguma ideia ? Nao consigo achar uma boa solução na internet

**Comment by caiovfernandes** [comment]
Tenta **control + C**.

**Comment by ErickGiffoni** [comment]
Pessoal, estou tendo um novo problema. Como não encontro a solução, postei ele no stackverflow. Se alguém souber me ajudar , agradeço. 
Post aqui : [https://stackoverflow.com/questions/55480736/mongoengine-connect-how-to-connect-to-another-port-that-is-not-default]()

**Comment by joaovitor3** [comment]
Aqui na documentação oficial do mongo tem um exemplo que fala sobre isso:
![image](https://user-images.githubusercontent.com/18130942/55427415-55202400-555d-11e9-990e-0b3d2376dd95.png)
Outro link útil:
- https://stackoverflow.com/questions/15666968/flask-mongoengine-connect-through-uri

**Comment by ErickGiffoni** [comment]
> Aqui na documentação oficial do mongo tem um exemplo que fala sobre isso:
> ![image](https://user-images.githubusercontent.com/18130942/55427415-55202400-555d-11e9-990e-0b3d2376dd95.png)
> Outro link útil:
> 
> * https://stackoverflow.com/questions/15666968/flask-mongoengine-connect-through-uri

Não adiantou muito, mas obrigado mano

**Comment by ErickGiffoni** [comment]
@caiovfernandes , comecei a fazer um programa para pegar os dados do telegram e jogar no banco. Ta dando meio errado. Dá uma olhada, por favor:

connectDataBase.py

```
import mongoengine
import Telegram

mongoengine.connect(db="Telegram_User_DataBase")#, alias="telegramUDB", host="MacBook-Pro-de-Erick.local:27017", port=27017)

chats = list() #lista de chats do 'tipo' Telegram
chat1 = Telegram() #erro 

chats.append(chat1)

chats[0].username = "chatopsMDS"
chats[0].users.append(User())
chats[0].users[0].newUser("erick", "giffoni", "erickgiff", "1567", False)
chats.save()
```

**Comment by vitorandos** [comment]
Se possível, coloca a mensagem de erro que aparece também.

**Comment by ErickGiffoni** [comment]
> Se possível, coloca a mensagem de erro que aparece também.

```
python3 connectDataBase.py 
Traceback (most recent call last):
  File "connectDataBase.py", line 12, in <module>
    chats[0].users.append(User())
AttributeError: module 'Telegram' has no attribute 'users'
```

**Comment by ErickGiffoni** [comment]
@grupe , estou tentando testar um código, mas os imports não funcionam.
### Erro : Traceback (most recent call last):
  #### File "data_services/service.py", line 2, in <module>
    from data.Repository import Repository
#### ModuleNotFoundError: No module named 'data'

Alguém pode ajudar? Não encontro a solução na internet e preciso seguir em frente!
