### ISSUE TITLE
DS11 - Eu, como desenvolvedor, quero conectar o Rasa ao Telegram para que a Ada possa conversar com o usuário.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#56]
## Descrição da Issue
Fazer conexão do Rasa ao Telegram para que a Ada possa conversar com o usuário.

### Tasks: 
- [x] Estabelecer a conexão do Rasa ao Telegram

**Comment by ateldyfilho** [comment]
@vitorandos descrever critérios de aceitação.

**Comment by guilherme-mendes** [comment]
Repositórios que ajudam na resolução da issue:
Awesome ChatOps - https://github.com/exAspArk/awesome-chatops
Chatops Lappis - https://github.com/lappis-unb/chatops

**Comment by ghost** [comment]
Link que ajuda a entender a relação entre Rasa, Telegram e Flask na criação do Bot:
https://www.xfgeek.com/view-xfgeek-blog?title=Building-AI-chatbot-using-Rasa-NLU%2C-Flask-and-Telegram

**Comment by guilherme-mendes** [comment]
Esclarecemos algumas dúvidas com o pessoal do Lappis sobre a conexão do Rasa ao Telegram e docker.

**Comment by guilherme-mendes** [comment]
API do Telegram - https://core.telegram.org/bots/api

**Comment by guilherme-mendes** [comment]
Primeira conexão com o bot por meio do Telegram realizada. 
@lucasfcm9 
![Captura de tela de 2019-04-04 15-28-08](https://user-images.githubusercontent.com/37874689/55579462-aa3f6f80-56ee-11e9-8c2a-cd35b77156ee.png)

**Comment by ghost** [comment]
Exemplo de conversa com o Bot, primeira conexão realizada! 
@guilherme-mendes 

<img width="992" alt="Captura de Tela 2019-04-04 às 15 36 40" src="https://user-images.githubusercontent.com/40740008/55579857-97796a80-56ef-11e9-967a-ecfff955bff9.png">

**Comment by guilherme-mendes** [comment]
Utilizamos **ngrok** para realizarmos testes pois para usar o Telegram precisa-se de um servidor com SSL (cadeado verde).
@lucasfcm9
