### ISSUE TITLE
Treinamento de Docker

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#57]
## Descrição
Fazer um treinamento para a equipe de MDS de como utilizar a ferramenta Docker.
### Tasks
- [x] Idealizar a apresentação
- [x] Apresentar o Docker
- [x] Ensinar comandos mais utilizados

**Comment by vitorandos** [comment]
Além do que foi mostrado pelo João Vítor no treinamento, quem usa Mac ou Windows pode baixar o Docker Destop App em vez de instalá-lo através do terminal. 

`https://www.docker.com/products/docker-desktop`

**Comment by joaovitor3** [comment]
Foi realizado o treinamento de docker nesse [repositório](https://github.com/joaovitor3/treinamento-flask-mongo).

No treinamento os membros de MDS deviam realizar um post em uma rota e inserir o conteúdo recebido via JSON no banco de dados em mongo através de bibliotecas do flask.
Sendo essas tecnologias utilizadas através de container docker.
