### ISSUE TITLE
Criação do template de commits

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#6]
Nessa issue deve ser realizada a criação do template de commits. O template deve conter o passo a passo de como deve ser feito um commit.

### Task
- [x] Elaboração do template de commits, desde o conteúdo da mensagem até a conjugação verbal.

**Comment by vitorandos** [comment]
Critérios de aceitação:
- [x] Template de commits coerente ao projeto, permitindo rastreamento do commit para sua issue correspondente.
