### ISSUE TITLE
Evolução do Documento de Arquitetura

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#60]
## Descrição da Issue
Evoluir documento de arquitetura com as considerações discutidas na _Sprint Review_.

### Tasks: 
- [x] Elaborar tópicos incompletos ou faltantes
- [x] Disponibilizar no GH-Pages

**Comment by ErickGiffoni** [comment]
@todos , o diagrama da classe User do tópico 5.1 do Documento está finalizado ? Já posso implementar ??

**Comment by ErickGiffoni** [comment]
@sudjoao , não estou entendendo o diagrama de classes do documento. 
Por exemplo, um User tem vários Telegram ?

**Comment by sudjoao** [comment]
@ErickGiffoni provavelmente devo ter colocado a relação ao contrário, vou dar uma olhada no diagrama todo e quando estiver pronto te aviso.
