### ISSUE TITLE
US04 - Eu, como usuário, desejo ser cumprimentado pela Ada para iniciar uma conversa.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#87]
## Descrição da Issue
Eu, como usuário, desejo ser cumprimentado pela Ada para iniciar uma conversa.

### Tasks: 

- [x] Elaborar roteiro

### Critérios de aceitação

- [x] Interação condizente com a personalidade da ADA
- [x] Estar em Português Brasileiro

**Comment by ErickGiffoni** [comment]
Comecei os trabalhos nessa história. Entretanto, acho que para que eu consiga testar as mudanças preciso ter os arquivos feitos pelo @lucasfcm9 e @guilherme-mendes , já que eles que iniciaram o primeiro contato com a ADA via telegram. Dessa forma também saberei quais são os arquivos corretos para que eu efetue as mudanças necessárias para que a ADA possa cumprimentar o usuário e vice-versa. Por favor, respondam.
@joaovitor3

**Comment by joaovitor3** [comment]
@ErickGiffoni Acho que o guilherme enviou no sábado o .env com essas informações
Mas de qualquer forma vamos ver isso na daily

**Comment by ErickGiffoni** [comment]
Sim, enviou, mas são só variáveis de ambiente. Preciso dos códigos que funcionam a ADA.

**Comment by joaovitor3** [comment]
Acho que essas informações estão aqui no [instructions.md](https://github.com/fga-eps-mds/2019.1-ADA/blob/devel/ada/instructions.md)
Depois disso é só vc dar docker-compose up, que deve funcionar

**Comment by ErickGiffoni** [comment]
### Links úteis:

- Rasa docs : [https://rasa.com/docs](url)

**Comment by ErickGiffoni** [comment]
Estou com o seguinte problema: ao subir o servidor da ADA usando o comando 
```
docker-compose -f docker-compose-dev.yml --build
``` 
eu consigo subir o servidor, porém o bot não responde às mensagens no telegram. 
Tenho receio que isso possa ser pelo fato de eu já haver mudado alguns dados dos arquivos da Ada, como o domain.yml e o stories.md . 

Any clue ?

**Comment by joaovitor3** [comment]
@ErickGiffoni Não esqueça de exportar todas as variáveis de ambiente( BOT_NAME, ACCESS_TOKEN, WEBHOOK_URL)

**Comment by ErickGiffoni** [comment]
> @ErickGiffoni Não esqueça de exportar todas as variáveis de ambiente( BOT_NAME, ACCESS_TOKEN, WEBHOOK_URL)

Talvez o problema seja esse :
```
rasa-nlu 0.14.1 has requirement coloredlogs~=9.0, but you'll have coloredlogs 10.0 which is incompatible.
rasa-nlu 0.14.1 has requirement packaging~=17.1, but you'll have packaging 18.0 which is incompatible.
```

**Comment by ErickGiffoni** [comment]
ou...
```
"Please install {}".format(", ".join(failed_imports)))
ada_1    | Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install spacy
ada_1    | Makefile:2: recipe for target 'train-nlu' failed
ada_1    | make: *** [train-nlu] Error 1
20191-grupo-3_ada_1 exited with code 2
```

**Comment by ErickGiffoni** [comment]
Alguém sabe resolver isso ? 
```
Recreating 20191-grupo-3_mongo-telegram_1 ... error

ERROR: for 20191-grupo-3_mongo-telegram_1  Cannot start service mongo-telegram: b'Mounts denied: \r\nThe path /mongo_telegram\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -Recreating 20191-grupo-3_ada_1            ... done
r more info.\r\n.'

ERROR: for mongo-telegram  Cannot start service mongo-telegram: b'Mounts denied: \r\nThe path /mongo_telegram\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.

```

**Comment by joaovitor3** [comment]
@ErickGiffoni Esse é o erro que resolvemos anteriormente de criação de volume, você tem que criar uma pasta com o mesmo nome na sua pasta no primeiro diretório do volume no caso mongo_telegram, se não me engano. Se isso der errado cria uma pasta no diretório inicial com mongo-telegram

**Comment by ErickGiffoni** [comment]
História finalizada. Pull request feito.
Aguardo revisão.
12/04/2019 - 10:20h
