### ISSUE TITLE
Treinamento de GitLab/Rasa

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#93]
## Descrição da Issue
Fazer treinamento de GitLab/Rasa para MDS

### Tasks: 
- [x] MDS conseguir fazer requisições do GitLab usando o OUTH Token
- [x] MDS conseguir subir a aplicação usando docker/Rasa

**Comment by joaovitor3** [comment]
Não foi realizado um treinamento específico, porém foi realizado pareamento com os membros de MDS para a realização das tasks.
Dessa forma acredito que a issue pode ser fechada
